# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nick/codeShare/Projects/umake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nick/codeShare/Projects/umake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nick/codeShare/Projects/umake/CMakeFiles /home/nick/codeShare/Projects/umake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nick/codeShare/Projects/umake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named umake

# Build rule for target.
umake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 umake
.PHONY : umake

# fast build rule for target.
umake/fast:
	$(MAKE) -f CMakeFiles/umake.dir/build.make CMakeFiles/umake.dir/build
.PHONY : umake/fast

boilerplate.o: boilerplate.cpp.o

.PHONY : boilerplate.o

# target to build an object file
boilerplate.cpp.o:
	$(MAKE) -f CMakeFiles/umake.dir/build.make CMakeFiles/umake.dir/boilerplate.cpp.o
.PHONY : boilerplate.cpp.o

boilerplate.i: boilerplate.cpp.i

.PHONY : boilerplate.i

# target to preprocess a source file
boilerplate.cpp.i:
	$(MAKE) -f CMakeFiles/umake.dir/build.make CMakeFiles/umake.dir/boilerplate.cpp.i
.PHONY : boilerplate.cpp.i

boilerplate.s: boilerplate.cpp.s

.PHONY : boilerplate.s

# target to generate assembly for a file
boilerplate.cpp.s:
	$(MAKE) -f CMakeFiles/umake.dir/build.make CMakeFiles/umake.dir/boilerplate.cpp.s
.PHONY : boilerplate.cpp.s

parseMicrocontroller.o: parseMicrocontroller.cpp.o

.PHONY : parseMicrocontroller.o

# target to build an object file
parseMicrocontroller.cpp.o:
	$(MAKE) -f CMakeFiles/umake.dir/build.make CMakeFiles/umake.dir/parseMicrocontroller.cpp.o
.PHONY : parseMicrocontroller.cpp.o

parseMicrocontroller.i: parseMicrocontroller.cpp.i

.PHONY : parseMicrocontroller.i

# target to preprocess a source file
parseMicrocontroller.cpp.i:
	$(MAKE) -f CMakeFiles/umake.dir/build.make CMakeFiles/umake.dir/parseMicrocontroller.cpp.i
.PHONY : parseMicrocontroller.cpp.i

parseMicrocontroller.s: parseMicrocontroller.cpp.s

.PHONY : parseMicrocontroller.s

# target to generate assembly for a file
parseMicrocontroller.cpp.s:
	$(MAKE) -f CMakeFiles/umake.dir/build.make CMakeFiles/umake.dir/parseMicrocontroller.cpp.s
.PHONY : parseMicrocontroller.cpp.s

processTargets.o: processTargets.cpp.o

.PHONY : processTargets.o

# target to build an object file
processTargets.cpp.o:
	$(MAKE) -f CMakeFiles/umake.dir/build.make CMakeFiles/umake.dir/processTargets.cpp.o
.PHONY : processTargets.cpp.o

processTargets.i: processTargets.cpp.i

.PHONY : processTargets.i

# target to preprocess a source file
processTargets.cpp.i:
	$(MAKE) -f CMakeFiles/umake.dir/build.make CMakeFiles/umake.dir/processTargets.cpp.i
.PHONY : processTargets.cpp.i

processTargets.s: processTargets.cpp.s

.PHONY : processTargets.s

# target to generate assembly for a file
processTargets.cpp.s:
	$(MAKE) -f CMakeFiles/umake.dir/build.make CMakeFiles/umake.dir/processTargets.cpp.s
.PHONY : processTargets.cpp.s

umake.o: umake.cpp.o

.PHONY : umake.o

# target to build an object file
umake.cpp.o:
	$(MAKE) -f CMakeFiles/umake.dir/build.make CMakeFiles/umake.dir/umake.cpp.o
.PHONY : umake.cpp.o

umake.i: umake.cpp.i

.PHONY : umake.i

# target to preprocess a source file
umake.cpp.i:
	$(MAKE) -f CMakeFiles/umake.dir/build.make CMakeFiles/umake.dir/umake.cpp.i
.PHONY : umake.cpp.i

umake.s: umake.cpp.s

.PHONY : umake.s

# target to generate assembly for a file
umake.cpp.s:
	$(MAKE) -f CMakeFiles/umake.dir/build.make CMakeFiles/umake.dir/umake.cpp.s
.PHONY : umake.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... umake"
	@echo "... boilerplate.o"
	@echo "... boilerplate.i"
	@echo "... boilerplate.s"
	@echo "... parseMicrocontroller.o"
	@echo "... parseMicrocontroller.i"
	@echo "... parseMicrocontroller.s"
	@echo "... processTargets.o"
	@echo "... processTargets.i"
	@echo "... processTargets.s"
	@echo "... umake.o"
	@echo "... umake.i"
	@echo "... umake.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

