name: Linux build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        pip3 install pyinstaller
        pyinstaller --onefile ./umake.py
        chmod +x dist/umake

#bump release if successful

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "stable-lin"
        prerelease: false
        title: "Linux Stable Build"
        files: |
          dist/umake